---
# file: tasks/common.yml

- name: 'Check if {{ job_name }} job presents'
  uri:
    url: '{{ job_check_link }}/{{ job_name }}'
    force_basic_auth: yes
    user: '{{ jenkins_admin_login }}'
    password: '{{ jenkins_admin_token }}'
    status_code: 200, 404
  register: jobCheck

- name: 'Create {{ job_name }} job if doesnt exist'
  uri:
    url: '{{ job_create_link }}?name={{ job_name }}'
    method: POST
    headers:
      Content-Type: "text/xml"
    force_basic_auth: yes
    user: '{{ jenkins_admin_login }}'
    password: '{{ jenkins_admin_token }}'
    body: "{{ lookup('template', '{{ job_template }}.xml.j2') }}"
  changed_when: jobCheck.status == 404
  when: jobCheck.status == 404

- name: 'Check if {{ job_name }} configuration is OK'
  uri:
    url: '{{ job_check_link }}/{{ job_name }}/config.xml'
    method: POST
    force_basic_auth: yes
    user: '{{ jenkins_admin_login }}'
    password: '{{ jenkins_admin_token }}'
    body: "{{ lookup('template', '{{ job_template }}.xml.j2') }}"
  when: jobCheck.status != 404
