---
# file: tasks/version-2/main.yml

- name: set facts
  include: '{{ tasks_version_path }}/set_facts.yml'

- name: install all required jenkins plugins
  jenkins_plugin:
    name: '{{ item }}'
    url_username: '{{ jenkinsAdmin.name }}'
    url_password: '{{ jenkinsAdmin.password }}'
    url: '{{ jenkins_base_link }}'
    timeout: 60000
  with_items: '{{ jenkins_plugin_list }}'
  notify:
    - restart jenkins with token
    - load jenkins with token
- meta: flush_handlers

- name: 'create Service_Set_Status job'
  include: '{{ tasks_base_path }}/create-job.yml job_name=Service_Set_Status job_template={{ job_version_template_link }}/jobs/Service_Set_Status'
- name: generate all required build flows
  include: '{{ tasks_version_path }}/build_flow.yml buildFlowName={{ item }}'
  with_items: '{{ build_flows }}'
