---
# file: tasks/version-2/prepare-dispatcher.yml

- name: init variables
  set_fact:
    temp_template_link: "{{ jenkins_home }}/workspace/{{ project_name }}_Gene\
rate/{{ project_name_config }}/{{ project_name_config }}.dispatcher/src/environment"

- name: 'ensure that properties file for dispatchers  exists'
  template:
    src: "{{ job_version_template_link }}/dispatcher.properties.j2"
    dest: '{{ temp_template_link }}/{{ disp_item }}.properties'
    owner: '{{ jenkins_user }}'
  with_items:
    - 'disp_authors'
    - 'disp_publishers'
  loop_control:
    loop_var: disp_item
  become: True
