---
# file: tasks/version-2/set_facts.yml

- name: check if all required variables are defined
  fail:
    msg: '{{ item }} variable should be defined! Check Readme.rd (kb link)'
  when: item is undefined
  with_items:
    - build_flows

- name: initialize all required variables
  set_fact:
    jenkins_plugin_list:
      - workflow-aggregator
      - blueocean
      - gitlab-plugin
      - build-blocker-plugin
      - nexus-artifact-uploader
      - job-restrictions
      - http_request
      - pipeline-utility-steps
      - sonar-quality-gates
      - ssh-agent
      - sonar
      - jacoco
    env_types_list: []

- name: find all existing environment_types on AEM instances
  set_fact:
    env_types_list: "{{ env_types_list }} + [ '{% if hostvars[item]['environment_type'] is defined %}{{ hostvars[item]['environmen\
t_type'] }}{% else %}{{ environment_type }}{% endif %}' ]"
  with_items: "{{ groups['aem_instances'] }}"

- name: make this list unique
  set_fact:
    env_types_list: '{{ env_types_list|unique }}'
