---
# file: tasks/version-2/subtasks/find-render.yml

- name: 'find all authoring dispatchers  with render var'
  set_fact:
    disp_author_array: "{{ disp_author_array + [ findRender ] }}"
    envAuthorDispatchers: "{{ envAuthorDispatchers + [ findRender ] }}"
  when: renderItem in aemAuthorArray
  with_items: "{{ hostvars[findRender]['render'].split(',') }}"
  loop_control:
    loop_var: renderItem

- name: 'find all publishing dispatchers  with render var'
  set_fact:
    disp_publish_array: "{{ disp_publish_array + [ findRender ] }}"
    envPublishDispatchers: "{{ envPublishDispatchers + [ findRender ] }}"
  when: renderItem in aemPublishArray
  with_items: "{{ hostvars[findRender]['render'].split(',') }}"
  loop_control:
    loop_var: renderItem
